from setuptools import setup, find_packages

setup(
    name="flask_network_lab",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Flask==2.3.3',
        'flask-socketio==5.3.4',
        'python-on-whales==0.74.0',
        'eventlet==0.33.3',
        'gevent==22.10.2',
        'gevent-websocket==0.10.1',
        'python-engineio==4.6.0',
        'python-socketio==5.8.0',
        'docker==7.0.0',
        'Werkzeug==2.3.7',
        'click==8.1.7',
        'itsdangerous==2.1.2',
        'Jinja2==3.1.2',
        'MarkupSafe==2.1.3',
        'dnspython==2.4.2',
        'requests==2.31.0',
        'urllib3==2.0.7',
        'certifi==2023.11.17',
        'charset-normalizer==3.3.2',
        'idna==3.4',
        'python-dotenv==1.0.0',
        'structlog==23.2.0',
    ],
    extras_require={
        'windows': ['pywin32==306'],
    },
    python_requires='>=3.8',
    author="Your Name",
    author_email="your.email@example.com",
    description="Flask Network Lab - 네트워크 실습 환경을 위한 웹 기반 터미널",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/flask_network_lab",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Education",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
) 