version: "3"

services:
    attacker:
        image: handsonsecurity/seed-ubuntu:large
        container_name: seed-attacker
        tty: true
        cap_add:
            - ALL
        privileged: true
        ports:
            - "4200:4200"
        volumes:
            - ./volumes:/volumes
            - ./init.sh:/init.sh
        hostname: attacker
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.105
        command: /init.sh

    hostA:
        image: handsonsecurity/seed-ubuntu:large
        container_name: hostA-10.9.0.5
        tty: true
        cap_add:
            - ALL
        volumes:
            - ./init.sh:/init.sh
        ports:
            - "4201:4200"
        hostname: hostA
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5
        command: bash -c "/etc/init.d/openbsd-inetd start && /init.sh && tail -f /dev/null"

    hostB:
        image: handsonsecurity/seed-ubuntu:large
        container_name: hostB-10.9.0.6
        tty: true
        cap_add:
            - ALL
        ports:
            - "4202:4200"
        volumes:
            - ./init.sh:/init.sh
        hostname: hostB
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
        command: bash -c "/etc/init.d/openbsd-inetd start && /init.sh && tail -f /dev/null"

networks:
    net-10.9.0.0:
        ipam:
            config:
                - subnet: 10.9.0.0/24
